default_agent: firstagent
is_agentcore_create_with_iac: true
agents:
  firstagent:
    name: firstagent
    entrypoint: /home/vidit68/Desktop/Hackathon/aws/FirstAgent/src/main.py
    deployment_type: container
    source_path: /home/vidit68/Desktop/Hackathon/aws/FirstAgent/src
    aws:
      account: null
      region: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    is_generated_by_agentcore_create: true
